### ISSUE TITLE
dangling pointers in ImportData constructor

### ISSUE THREAD

**Issue by proppy** [xlsynth/xlsynth-crate#32]
https://github.com/xlsynth/xlsynth-crate/blob/2e93d32734be5b414787728b984e67e3d056e980/xlsynth/src/dslx.rs#L54 will create a owned `CString` that will go out of scope at each iteration of the for loop, creating dangling `*const std::os::raw::c_char` that will get accumulated in the outer `Vec`.

It should probably create to an owned `Vec<CString>` first before being converted to an array of raw pointer for interop (using `map`)?

**Comment by cdleary** [comment]
@proppy Thanks for flagging! One thing that's definitely harder with a release DSO build separation is a nice integrated ASAN like one gets with a monorepo. Also me being a noob at Rust / C ABI interop best practices.

Maybe I'll add a valgrind test after/as I fix this given the binary linkage.

**Comment by proppy** [comment]
> One thing that's definitely harder with a release DSO build separation is a nice integrated ASAN like one gets with a monorepo

Maybe there is  a way to integrate everything in a monorepo, while still releasing separate artifacts?

The rust folks seems to be using `git subtree` or https://github.com/josh-project/josh/ depending of the subproject.

**Comment by proppy** [comment]
> Thanks for flagging!

@cdleary will extend your thanks to the internal crabal 🦀 reviewer :)

**Comment by cdleary** [comment]
> > Thanks for flagging!
> 
> 
> 
> @cdleary will extend your thanks to the internal crabal 🦀 reviewer :)

100% please do!
